// ============================================
// BOT MASTER PLATFORM - MAIN WORKER
// DO NOT EDIT THIS FILE
// ============================================

// Load environment variables
const BOT_TOKEN = process.env.BOT_TOKEN || 'YOUR_BOT_TOKEN';
const PLATFORM_NAME = process.env.PLATFORM_NAME || 'Bot Master Platform';

// Import engine modules
import { loadAllFeatures } from './engine/loader.js';
import { createContext } from './engine/context.js';
import { dispatchEvent } from './engine/dispatcher.js';
import { handleApiRequest } from './engine/api.js';

// Global state
let features = [];
let versions = [];

// Load master configuration
let masterConfig = {};
try {
  masterConfig = JSON.parse(await fetch('./master.json').then(r => r.text()));
} catch (e) {
  console.error('Failed to load master.json:', e);
}

// Initialize the platform
async function initializePlatform() {
  console.log(`🚀 Initializing ${PLATFORM_NAME}...`);
  
  // Load all features from versions
  const loadResult = await loadAllFeatures();
  features = loadResult.features;
  versions = loadResult.versions;
  
  console.log(`✅ Loaded ${features.length} features from ${versions.length} versions`);
  
  return { features, versions };
}

// Handle Telegram webhook
async function handleTelegramUpdate(update) {
  try {
    // Create context from update
    const ctx = createContext(update, BOT_TOKEN);
    
    // Dispatch to features
    const result = await dispatchEvent(ctx, features);
    
    return {
      success: true,
      processed: result.processed,
      responses: result.responses
    };
  } catch (error) {
    console.error('Error handling update:', error);
    return { success: false, error: error.message };
  }
}

// Main fetch handler
export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    
    // Health check endpoint
    if (url.pathname === '/health') {
      return new Response(JSON.stringify({
        status: 'online',
        platform: PLATFORM_NAME,
        versions: versions.length,
        features: features.length,
        timestamp: new Date().toISOString()
      }), {
        headers: { 'Content-Type': 'application/json' }
      });
    }
    
    // Set webhook endpoint
    if (url.pathname === '/set-webhook' && request.method === 'POST') {
      const webhookUrl = `${url.origin}/webhook`;
      const response = await fetch(`https://api.telegram.org/bot${BOT_TOKEN}/setWebhook?url=${webhookUrl}`);
      return new Response(await response.text());
    }
    
    // Webhook endpoint for Telegram
    if (url.pathname === '/webhook' && request.method === 'POST') {
      const update = await request.json();
      
      // Process update asynchronously
      ctx.waitUntil(handleTelegramUpdate(update));
      
      return new Response('OK');
    }
    
    // API endpoints
    if (url.pathname.startsWith('/api/')) {
      return handleApiRequest(request, env);
    }
    
    // Initialize on first request
    if (!features.length) {
      await initializePlatform();
    }
    
    // Default response
    return new Response(JSON.stringify({
      message: 'Bot Master Platform',
      status: 'running',
      endpoints: ['/health', '/webhook', '/set-webhook', '/api/*']
    }), {
      headers: { 'Content-Type': 'application/json' }
    });
  }
};
